/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fabtimeclocksystem.main;

import com.fabtimeclocksystem.db.TimeClockIO;
import java.awt.Color;
import java.awt.Image;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.Timer;

/**
 *
 * @author faith
 */
public class TimeClockForm extends javax.swing.JFrame {
    public ArrayList<String> newList = new ArrayList<>();
    public Boolean found = false;
    /**
     * Creates new form TimeClock
     */
    public TimeClockForm() {
        initComponents();
        
        //set icon
        Image logo = Toolkit.getDefaultToolkit().getImage("src/com/fabtimeclocksystem/resources/appIcon.png");
        this.setIconImage(logo);

        //set location of frame on screen to center
        this.setLocationRelativeTo(null);

        //set background color of frame
        this.getContentPane().setBackground(new Color(51, 51, 51));
        
        
        setTime();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClockIn = new javax.swing.JButton();
        btnClockOut = new javax.swing.JButton();
        txtBadgeNum = new javax.swing.JTextField();
        lblTimeClockHeader = new javax.swing.JLabel();
        lblBadgeNum = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClockIn.setBackground(new java.awt.Color(18, 185, 150));
        btnClockIn.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnClockIn.setText("Punch-In");
        btnClockIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockInActionPerformed(evt);
            }
        });

        btnClockOut.setBackground(new java.awt.Color(18, 185, 150));
        btnClockOut.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnClockOut.setText("Punch-Out");
        btnClockOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockOutActionPerformed(evt);
            }
        });

        txtBadgeNum.setFont(new java.awt.Font("Dialog.plain", 0, 24)); // NOI18N

        lblTimeClockHeader.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        lblTimeClockHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeClockHeader.setText("Fab Systems");

        lblBadgeNum.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblBadgeNum.setForeground(new java.awt.Color(255, 255, 255));
        lblBadgeNum.setText("Badge#");

        lblClock.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 255, 255));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(lblTimeClockHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnClockIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblBadgeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBadgeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnClockOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblTimeClockHeader)
                .addGap(25, 25, 25)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBadgeNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBadgeNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(btnClockIn)
                .addGap(18, 18, 18)
                .addComponent(btnClockOut)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClockInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockInActionPerformed
        String badge = txtBadgeNum.getText();
      
        String punchIn = "In";
        
        TimeClockIO tcio = new TimeClockIO();
        try {
            tcio.timePunch(badge, punchIn, getCurrentDate());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TimeClockForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TimeClockForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TimeClockForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtBadgeNum.setText("");
    }//GEN-LAST:event_btnClockInActionPerformed

    private void btnClockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockOutActionPerformed
        String badge = txtBadgeNum.getText();
     
        String punchOut = "Out";
        
        TimeClockIO tcio = new TimeClockIO();
        try {
            tcio.timePunch(badge, punchOut, getCurrentDate());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TimeClockForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TimeClockForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TimeClockForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtBadgeNum.setText("");  
    }//GEN-LAST:event_btnClockOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeClockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeClockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeClockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeClockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeClockForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClockIn;
    private javax.swing.JButton btnClockOut;
    private javax.swing.JLabel lblBadgeNum;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblTimeClockHeader;
    private javax.swing.JTextField txtBadgeNum;
    // End of variables declaration//GEN-END:variables

    public java.sql.Timestamp getCurrentDate(){
        java.util.Date today = new java.util.Date();
        return new java.sql.Timestamp(today.getTime());
    }
    
    public void setTime(){
      int delay = 100;
      Timer timer = new Timer(delay, new ActionListener() {

          @Override
	  public void actionPerformed(ActionEvent e) {
	     LocalDateTime date = LocalDateTime.now();
	     DateTimeFormatter formatter = DateTimeFormatter.ofPattern("E, MMM dd yyyy hh:mm a");
	     String formattedDateTime = date.format(formatter);
	     lblClock.setText(formattedDateTime);
	  }
      });

      timer.start();
    }
        
}

