/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fabpointofsalesystem.main;

import com.fabpointofsalesystem.db.OrderIO;
import com.fabpointofsalesystem.login.LoginForm;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author faith
 */
public class PointOfSaleForm extends javax.swing.JFrame {
    private DefaultTableModel cartModel;
    /**
     * Creates new form PointOfSaleForm
     */
    public PointOfSaleForm() {
        initComponents();
        
        //set icon
        Image logo = Toolkit.getDefaultToolkit().getImage("src/com/fabpointofsalesystem/resources/appIcon.png");
        this.setIconImage(logo);

        //set location of frame on screen to center
        this.setLocationRelativeTo(null);

        //set background color of frame
        this.getContentPane().setBackground(new Color(51, 51, 51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        pnlPOS = new javax.swing.JPanel();
        lblOrderId = new javax.swing.JLabel();
        txtSkuLookup = new javax.swing.JTextField();
        lblSubTotal = new javax.swing.JLabel();
        lblQuantityLookup = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtQuantityLookup = new javax.swing.JTextField();
        lblTax = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();
        txtTax = new javax.swing.JTextField();
        btnUpdateCartItem = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnDeleteCartItem = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        btnCashPayment = new javax.swing.JButton();
        btnCardPayment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPOSHeader = new javax.swing.JLabel();
        lblOrderIdHeader = new javax.swing.JLabel();
        lblSkuLookup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FAB Point of Sale System");
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fabsystems/resources/logout.png"))); // NOI18N
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fabsystems/resources/logout2.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Dialog.plain", 1, 20)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(860, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnLogout)
                .addGap(189, 189, 189))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        getContentPane().add(pnlMenu);

        pnlPOS.setBackground(new java.awt.Color(51, 51, 51));

        lblOrderId.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        lblOrderId.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderId.setText("0");

        lblSubTotal.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTotal.setText("Subtotal");

        lblQuantityLookup.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblQuantityLookup.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantityLookup.setText("Quantity");

        lblTax.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblTax.setForeground(new java.awt.Color(255, 255, 255));
        lblTax.setText("Tax%");

        btnAddToCart.setBackground(new java.awt.Color(18, 185, 150));
        btnAddToCart.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        btnUpdateCartItem.setBackground(new java.awt.Color(18, 185, 150));
        btnUpdateCartItem.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnUpdateCartItem.setText("Update Cart Item");

        lblTotal.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");

        btnDeleteCartItem.setBackground(new java.awt.Color(18, 185, 150));
        btnDeleteCartItem.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnDeleteCartItem.setText("Delete Cart Item");

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Sku", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCart);

        btnCashPayment.setBackground(new java.awt.Color(18, 185, 150));
        btnCashPayment.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCashPayment.setText("Cash Payment");

        btnCardPayment.setBackground(new java.awt.Color(18, 185, 150));
        btnCardPayment.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCardPayment.setText("Card Payment");

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cart");

        lblPOSHeader.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblPOSHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblPOSHeader.setText("Product Lookup");

        lblOrderIdHeader.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblOrderIdHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderIdHeader.setText("Order ID");

        lblSkuLookup.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblSkuLookup.setForeground(new java.awt.Color(255, 255, 255));
        lblSkuLookup.setText("Sku");

        javax.swing.GroupLayout pnlPOSLayout = new javax.swing.GroupLayout(pnlPOS);
        pnlPOS.setLayout(pnlPOSLayout);
        pnlPOSLayout.setHorizontalGroup(
            pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPOSLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPOSHeader)
                    .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAddToCart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateCartItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteCartItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblQuantityLookup)
                    .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtQuantityLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPOSLayout.createSequentialGroup()
                            .addComponent(lblSkuLookup)
                            .addGap(62, 62, 62)
                            .addComponent(txtSkuLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlPOSLayout.createSequentialGroup()
                            .addComponent(lblOrderIdHeader)
                            .addGap(18, 18, 18)
                            .addComponent(lblOrderId))
                        .addComponent(jLabel1))
                    .addGroup(pnlPOSLayout.createSequentialGroup()
                        .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPOSLayout.createSequentialGroup()
                                .addComponent(lblSubTotal)
                                .addGap(27, 27, 27)
                                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTax)
                                .addGap(28, 28, 28)
                                .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(lblTotal)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPOSLayout.createSequentialGroup()
                                .addComponent(btnCashPayment)
                                .addGap(18, 18, 18)
                                .addComponent(btnCardPayment)
                                .addGap(235, 235, 235)))
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139))
        );
        pnlPOSLayout.setVerticalGroup(
            pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPOSLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPOSHeader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderIdHeader)
                    .addComponent(lblOrderId))
                .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPOSLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSkuLookup)
                            .addComponent(txtSkuLookup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantityLookup)
                            .addComponent(txtQuantityLookup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(btnAddToCart)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateCartItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteCartItem))
                    .addGroup(pnlPOSLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSubTotal)
                        .addComponent(lblTax)
                        .addComponent(lblTotal)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pnlPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCashPayment)
                    .addComponent(btnCardPayment))
                .addGap(106, 106, 106))
        );

        getContentPane().add(pnlPOS);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        validateLookupInputs();
        
    }//GEN-LAST:event_btnAddToCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PointOfSaleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnCardPayment;
    private javax.swing.JButton btnCashPayment;
    private javax.swing.JButton btnDeleteCartItem;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateCartItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblOrderIdHeader;
    private javax.swing.JLabel lblPOSHeader;
    private javax.swing.JLabel lblQuantityLookup;
    private javax.swing.JLabel lblSkuLookup;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPOS;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtQuantityLookup;
    private javax.swing.JTextField txtSkuLookup;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
    
    //method that works with login variable to display username in menu
    public void username(String user) {
        lblUser.setText(user);
    }
    
    //clears lookup fields for next entry
    public void clearLookupFields() {
        txtSkuLookup.setText("");
        txtQuantityLookup.setText("");
    }

    //clears subTotal, tax, and total if 0 items in cart
    public void clearCheckoutFields() {
        txtSubTotal.setText("");
        txtTax.setText("");
        txtTotal.setText("");
    }
    
    //validates lookup fields for correct data
    private boolean validateLookupInputs() {
        String sku = txtSkuLookup.getText();
        String quantity = txtQuantityLookup.getText();

        // account for sku being empty
        if (sku.isBlank()) {
            JOptionPane.showMessageDialog(this, "Sku cannot be blank.",
                    "Name Error", JOptionPane.ERROR_MESSAGE);
            txtSkuLookup.requestFocusInWindow();
            return false;
        }

        // account for quantity being empty
        if (quantity.isBlank()) {
            JOptionPane.showMessageDialog(this, "Quantity cannot be blank.",
                    "Quantity Error", JOptionPane.ERROR_MESSAGE);
            txtQuantityLookup.requestFocusInWindow();
            return false;
        }

        //make sure quantity is a number
        try {
            Integer.parseInt(quantity);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity must be a number.",
                    "Quantity Error", JOptionPane.ERROR_MESSAGE);
            txtQuantityLookup.setText("");
            txtQuantityLookup.requestFocusInWindow();
            return false;
        }
        //make sure quantity is greater than 0
        if (Integer.parseInt(quantity) <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Quantity must be a number greater than 0.",
                    "Quantity Error", JOptionPane.ERROR_MESSAGE);
            txtQuantityLookup.setText("");
            txtQuantityLookup.requestFocusInWindow();
            return false;
        }
        return true;
    }
    
    //combines add order and update order methods from OrderIO since it can be called for different payment methods
    public void saveOrder() {
        OrderIO oio = new OrderIO();
        cartModel = (DefaultTableModel) tblCart.getModel();
        Double total = Double.parseDouble(txtTotal.getText());
        java.util.Date date = new java.util.Date();
        String dateString = date.toString();
        int id = Integer.parseInt(lblOrderId.getText());

        try {
            oio.addOrder(id, total, dateString);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int rows = tblCart.getRowCount();
        for (int i = 0; i < rows; i++) {
            String name = (String) tblCart.getValueAt(i, 1);
            int q = (int) tblCart.getValueAt(i, 3);

            try {
                oio.updateProductCounts(q, name);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    
    //retrieve data to insert into mysql order items table
    public void saveOrderItems() {
        OrderIO oio = new OrderIO();
        cartModel = (DefaultTableModel) tblCart.getModel();
        int rows = tblCart.getRowCount();

        for (int i = 0; i < rows; i++) {
            int qty = (int) tblCart.getValueAt(i, 3);
            int pid = (int) tblCart.getValueAt(i, 0);
            int oid = Integer.parseInt(lblOrderId.getText());

            try {
                oio.addOrderItems(qty, pid, oid);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        clearCheckoutFields();

        for (int j = rows - 1; j >= 0; j--) {
            cartModel.removeRow(j);
        }
        
        int oId;
        try {
            oId = oio.retrieveOrderRowCount() + 1;
            lblOrderId.setText(String.valueOf(oId));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //save payment type for payments to be stored in mysql
    public void savePayment(String payType) throws ClassNotFoundException, SQLException {
        OrderIO oio = new OrderIO();

        oio.addPayment(payType);
    }
    
    
    
    public String generateString() {
        String uuid = UUID.randomUUID().toString().substring(0,6);
        return uuid;
    }
}
